version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - DEBUG=True
      - RENDER=False
      - STRIPE_SECRET_KEY=sk_test_51QNz74Iv9qvHVp1BfKIIBypQpXXBYdonnP8iPF34HBavh79ulki50xzMJcSMOFJ0sa1leImx7gPQBfbKNw5MjgZH00I8AxqRB7
      - STRIPE_PUBLIC_KEY=pk_test_51QNz74Iv9qvHVp1Be78jH8A0HA6E8pXRZ6nAnRn1hdwp3uwJmjr0WRVIcuD86Wn3BZKXYBlyodhGugxTocMpRDL500TlbAPRFK
      - SECRET_KEY=django-insecure-7tizj0=&m^ze&v+vt*9gk7tu$@ba-usg2@9&zmww74g^i5=n0g
      - DATABASE_URL=postgresql://escapadas_db_user:7VJSjOWhOpb4J9n4MCGBD1j7PRdOpsdu@dpg-ct1kv7t6l47c73bgfo9g-a.frankfurt-postgres.render.com/escapadas_db
      - ALLOWED_HOSTS=127.0.0.1,localhost,0.0.0.0
      - CLOUD_NAME=dmeutgmug
      - CLOUD_API_KEY=465878973727888
      - CLOUD_API_SECRET_KEY=O_kTgi4JDqlspQ9O5POlbw6XSsQ 
